simulation:
  start_date: 2024-01-01
  end_date: 2024-12-31
  n_simulations: 100

market:
  power:
    volatility: 0.2
    fwd_curve:
      - 80
      - 83
      - 86
      - 89
      - 92
      - 95
      - 100
      - 105
      - 110
      - 115
      - 120
      - 125
  coal:
    volatility: 0.25
    fwd_curve:
      - 120
      - 128
      - 116
      - 104
      - 95
      - 85
      - 70
      - 95
      - 114
      - 120
      - 130
      - 110
  correlation: 0.7
  sigma_ou:
    power: 0.05
    coal: 0.07
  beta:
    power: 10.0
    coal: 15.0

plant:
  operation_costs: 2.0
  alpha: 1.0
  ramping_up_costs: 4.0
  ramping_down_costs: 3.0
  idle_costs: 0.02
  n_days_ramping_up: 1
  n_days_ramping_down: 1
  polynomial_degree: 3
