# Assets
POWER = "POWER"
COAL = "COAL"
SPREAD = "SPREAD"

# Simulation axes
SIMULATION_PATH = "SIMULATION_PATH"
SIMULATION_DAY = "SIMULATION_DAY"
ASSET = "ASSET"

# Output keys
KEY_DELTA_POSITION = "DELTA_POSITION"
KEY_PREDICTED = "PREDICTED"
KEY_RESIDUALS = "RESIDUALS"
KEY_R2 = "R2"

DELTA_POWER = "DELTA_POWER"
DELTA_COAL = "DELTA_COAL"

DELIVERY_START = "DELIVERY_START"


DIM_SIMULATION_DAY = "simulation_day"
DIM_SIMULATION_PATH = "simulation_path"
DIM_OPERATIONAL_STATE = "operational_state"


OPTIMAL_CONTROL = "optimal_control"
VALUE = "value"
CASHFLOWS = "cashflows"
REGRESSED_VALUE = "regressed_value"
REGRESSION_RESULTS = "regression_results"