# Assets
POWER = "POWER"
COAL = "COAL"
SPREAD = "SPREAD"

# Simulation axes
SIMULATION_PATH = "SIMULATION_PATH"
SIMULATION_DAY = "SIMULATION_DAY"
ASSET = "ASSET"

# Output keys
DELTA_POSITION = "DELTA_POSITION"
KEY_PREDICTED = "PREDICTED"
KEY_RESIDUALS = "RESIDUALS"
KEY_R2 = "R2"

DELTA_POWER = "DELTA_POWER"
DELTA_COAL = "DELTA_COAL"
DELTA_POSITION = "DELTA_POSITION"

DELIVERY_START = "DELIVERY_START"